name: EntercraftPermissions
version: ${build.number}
description: 'Cloud-friendly Bukkit permissions plugin'
load: STARTUP
authors:
  - Zenexer
website: 'http://e2m.co/'
main: 'co.e2m.mc.entercraft.permissions.plugin.EntercraftPermissionsPlugin'
depend:
  - Vault
loadbefore:
  - Essentials
  - WorldEdit
commands:
  perm:
    description: 'Base for all EntercraftPermissions commands'
    permission: 'entercraft.permissions.commands'
    usage: 'For help, use /<command> help'
    aliases:
      - perms
      - permissions
permissions:
  entercraft.permissions.commands:
    description: 'Allows access to EntercraftPermissions commands via /cp'
    children:
      entercraft.permissions.commands.version: true
      entercraft.permissions.commands.reload: true
  entercraft.permissions.commands.version:
    description: 'Outputs version information about EntercraftPermissions'
  entercraft.permissions.commands.reload:
    description: 'Reloads the EntercraftPermissions configuration YAML'