name: EntercraftPermissions
version: ${build.number}
description: 'Cloud-friendly Bukkit permissions plugin'
load: STARTUP
authors:
  - Zenexer
website: 'http://e2m.co/'
main: 'co.e2m.mc.entercraft.permissions.EntercraftPermissionsPlugin'
depend:
  - Vault
loadbefore:
  - Essentials
  - WorldEdit
commands:
  cp:
    description: 'Base for all EntercraftPermissions commands'
    permission: 'cloudpermissions.commands'
    usage: 'For help, use /<command> help'
    aliases:
      - cloudp
      - cperms
      - cloudpermissions
permissions:
  cloudpermissions.commands:
    description: 'Allows access to EntercraftPermissions commands via /cp'
    children:
      cloudpermissions.commands.version: true
      cloudpermissions.commands.reload: true
  cloudpermissions.commands.version:
    description: 'Outputs version information about EntercraftPermissions'
  cloudpermissions.commands.reload:
    description: 'Reloads the EntercraftPermissions configuration YAML'